openapi: 3.0.1
info:
  title: F1 Race Event Tracker API
  version: 1.0.0
  description: API to receive F1 race events and telemetry data.
paths:
  /race_events:
    get:
      operationId: app.get_race_events
      summary: Get race events by date range.
      description: Returns all race events whose date_created timestamp is within the provided start (inclusive) and end (exclusive) range.
      parameters:
        - in: query
          name: start_timestamp
          schema:
            type: integer
          required: true
          description: Start timestamp (inclusive)
        - in: query
          name: end_timestamp
          schema:
            type: integer
          required: true
          description: End timestamp (exclusive)
      responses:
        '200':
          description: Array of race event objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RaceEvent'
    post:
      operationId: app.submit_race_events
      summary: Submit race events
      description: Accepts F1 race event data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: string
                  format: uuid
                car_number:
                  type: integer
                lap_number:
                  type: integer
                event_type:
                  type: string
                timestamp:
                  type: integer
                trace_id:
                  type: string
              required:
                - event_id
                - car_number
                - lap_number
                - event_type
                - timestamp
                - trace_id
      responses:
        '201':
          description: Event submitted successfully.
        '200':
          description: Event submitted successfully.
  /telemetry_data:
    get:
      operationId: app.get_telemetry_data
      summary: Get telemetry events by date range.
      description: Returns all telemetry events whose date_created timestamp is within the provided start (inclusive) and end (exclusive) range.
      parameters:
        - in: query
          name: start_timestamp
          schema:
            type: integer
          required: true
          description: Start timestamp (inclusive)
        - in: query
          name: end_timestamp
          schema:
            type: integer
          required: true
          description: End timestamp (exclusive)
      responses:
        '200':
          description: Array of telemetry event objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TelemetryData'
    post:
      operationId: app.submit_telemetry_data
      summary: Submit telemetry data
      description: Accepts F1 driver telemetry data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                telemetry_id:
                  type: string
                  format: uuid
                car_number:
                  type: integer
                lap_number:
                  type: integer
                speed:
                  type: number
                fuel_level:
                  type: number
                rpm:
                  type: integer
                timestamp:
                  type: integer
                trace_id:
                  type: string
              required:
                - telemetry_id
                - car_number
                - lap_number
                - speed
                - fuel_level
                - rpm
                - timestamp
                - trace_id
      responses:
        '201':
          description: Telemetry data submitted successfully.
        '200':
          description: Telemetry data submitted successfully.
  /record_count:
    get:
      operationId: app.get_record_count
      summary: Get count of records in each table
      description: Returns the count of all rows for each event type.
      responses:
        '200':
          description: Count of records in each table.
          content:
            application/json:
              schema:
                type: object
                properties:
                  race_events:
                    type: integer
                  telemetry_data:
                    type: integer
  /event_ids:
    get:
      operationId: app.get_event_ids
      summary: Get list of race event IDs and trace IDs
      description: Returns a list containing the event ID and trace ID for each race event.
      responses:
        '200':
          description: List of race event IDs and trace IDs.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    event_id:
                      type: string
                      format: uuid
                    trace_id:
                      type: string
  /telemetry_ids:
    get:
      operationId: app.get_telemetry_ids
      summary: Get list of telemetry IDs and trace IDs
      description: Returns a list containing the telemetry ID and trace ID for each telemetry event.
      responses:
        '200':
          description: List of telemetry IDs and trace IDs.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    telemetry_id:
                      type: string
                      format: uuid
                    trace_id:
                      type: string
components:
  schemas:
    RaceEvent:
      type: object
      properties:
        event_id:
          type: string
          format: uuid
        car_number:
          type: integer
        lap_number:
          type: string
        event_type:
          type: string
        timestamp:
          type: integer
        trace_id:
          type: string
        date_created:
          type: integer
    TelemetryData:
      type: object
      properties:
        telemetry_id:
          type: string
          format: uuid
        car_number:
          type: integer
        lap_number:
          type: integer
        speed:
          type: integer
        fuel_level:
          type: integer
        rpm:
          type: integer
        timestamp:
          type: integer
        trace_id:
          type: string
        date_created:
          type: integer